{{- if ne .Values.olmVersion "v1" }}
{{- include "rhoai-operator.validateOverrides" . }}
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: {{ .Values.subscription.name }}
  namespace: {{ .Values.namespace.name }}
spec:
  channel: {{ include "rhoai-operator.subscriptionChannel" . }}
  installPlanApproval: {{ .Values.subscription.installPlanApproval }}
  name: {{ .Values.subscription.name }}
  source: {{ .Values.subscription.source }}
  sourceNamespace: {{ .Values.subscription.sourceNamespace }}
  startingCSV: {{ include "rhoai-operator.subscriptionStartingCSV" . }}
{{- end }}
