subscription:
  name: openshift-gitops-operator
  channel: latest
  installPlanApproval: Manual
  source: redhat-operators
  sourceNamespace: openshift-marketplace

namespace:
  name: openshift-gitops-operator
  displayName: Red Hat OpenShift GitOps

operatorGroup:
  name: openshift-gitops-operator
