# RHCL 1.4.x required for RHOAI 3.5 MaaS (Wasm shim bug fixed in 1.4.x).
# Previously pinned to 1.3.4 for RHOAI 3.4 due to a Wasm shim bug in 1.4.0.
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: rhcl-operator
  namespace: openshift-operators
spec:
  channel: stable
  installPlanApproval: Automatic
  name: rhcl-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
