{{- if ne .Values.olmVersion "v1" }}
---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: openshift-cert-manager-operator
  namespace: cert-manager-operator
  annotations:
    argocd.argoproj.io/sync-wave: "-05"
spec:
  channel: stable-v1
  name: openshift-cert-manager-operator
  source: redhat-operators
  sourceNamespace: openshift-marketplace
  installPlanApproval: Manual
  config:
    tolerations:
      - key: node-role.kubernetes.io/infra
        operator: Exists
    {{- if eq .Values.cloud "aws" }}
    env:
      - name: CLOUD_CREDENTIALS_SECRET_NAME
        value: aws-creds
    {{- end }}
{{- end }}
